config/routes.rb
Rails.application.routes.draw do
  root 'check#index'
  match 'check/index', via: [:get, :post]
  match 'check/result', via: [:get, :post]
  match 'check/upload_image', via: [:post]
  match 'check/delete_image', via: [:delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :file, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_controller.rb
class CheckController < ApplicationController
  protect_from_forgery :except => [:upload_image]

  require "phashion"
  require "dhash-vips"
  # require "open-uri"

  def index
    @image = Image.destroy_all
    ActiveRecord::Base.connection.execute("TRUNCATE images")
  end

  def result
    if params[:image_id]
      ##################################
      # Download Image
      ##################################
      # first_image_path = 'https://XXXXXXX'
      # open(first_image_path) { |image|
      #   File.open(first_image,"wb") do |file|
      #     file.puts image.read
      #   end
      # }
      image_id = params[:image_id].split(",")
      if image_id.size === 2
        @image_h = Hash.new { |h,k| h[k] = {} }
        file_path_r = Array.new
        image_id.each { |id|
          if Image.exists?(id: id)
            image = Image.find(id)
            @image_h[image.id]['image'] = image
            @image_h[image.id]['file_name'] = File.basename(image.file.path)
            file_path_r << getFilePath(image);
          end  
        }

        if params[:type] === '0'
          ##################################
          # Use of dhash-vips（IDHash）
          ##################################
          @type = 'libvips(IDHash)'
          calcIDHash(file_path_r)
          
        elsif params[:type] === '1'
          ##################################
          # Use of dhash-vips（DHash）
          ##################################
          @type = 'libvips(DHash)'
          calcDHash(file_path_r)
        else
          ##################################
          # Use of Phashion
          ##################################
          @type = 'ImageMagick'
          calcPhashion(file_path_r)
        end
      else
        logger.warn('[Invalid image_id]: ' + params[:image_id].inspect)
        redirect_to check_index_path, flash: {danger: 'Invalid Data (image_id)'}
      end
    else
      redirect_to check_index_path
    end
  end

  def upload_image
    image = Image.new params.require(:image).permit(:file)
    begin
      image.save!
      result = image
    rescue => e
      logger.error('[upload_image]:' + e.inspect)
      result = false
    end
    render status: 200, json: result, nothing: true
  end

  def delete_image
    if Image.exists?(id: params[:image_id])
      image = Image.find(params[:image_id])
      begin
        image.destroy!
        result = image
      rescue => e
        logger.error('[delete_image]:' + e.inspect)
        result = false
      end
    else
      result = true
    end
    render status: 200, json: result, nothing: true
  end

  private
    def getFilePath(image)
      tmp_file_path = image.file.url.gsub('/uploads/image', 'public/uploads/image')
      file_path = URI.decode(tmp_file_path).force_encoding('UTF-8')
      return file_path
    end

    def calcIDHash(file_path_r)
      hash1 = DHashVips::IDHash.fingerprint file_path_r[0]
      hash2 = DHashVips::IDHash.fingerprint file_path_r[1]
      @hamming_distance = DHashVips::IDHash.distance hash1, hash2
      decision(@hamming_distance)
    end

    def calcDHash(file_path_r)
      hash1 = DHashVips::DHash.calculate file_path_r[0]
      hash2 = DHashVips::DHash.calculate file_path_r[1]
      @hamming_distance = DHashVips::DHash.hamming hash1, hash2
      decision(@hamming_distance, 10, 20)
    end

    def calcPhashion(file_path_r)
      hash1 = Phashion::Image.new(file_path_r[0])
      hash2 = Phashion::Image.new(file_path_r[1])
      @hamming_distance = hash1.distance_from(hash2)
      decision(@hamming_distance)
    end

    def decision(hamming_distance, threshold1=15, threshold2 = 25)
      if hamming_distance == 0
        @result_message = 'Images are perfect matching'
        @bg_color = 'bg-success'
      elsif hamming_distance < threshold1
        @result_message = 'Images are very similar'
        @bg_color = 'bg-info'
      elsif hamming_distance < threshold2
        @result_message = 'Images are slightly similar'
        @bg_color = 'bg-warning'
      else
        @result_message = 'Images are different'
        @bg_color = 'bg-danger'
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_helper.rb
module CheckHelper
end

app/views/check/index.html.erb
<div class="container-fluid index-container">
    <h3>Check the similarity of the images</h3>

    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button>
            <%= message %>
        </div>
    <% end %>

    <%= form_with url: check_result_path, html: { class: "form-image" }, local: true do |f| %>
        <div class="form-group">
            <div class="row">
                <%= f.label :check_type %><br />
                <div class="col-md-12">
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-default active">
                            <%= f.radio_button :type, '0', {:checked => true} %>libvips(IDHash)
                        </label>
                        <label class="btn btn-default">
                            <%= f.radio_button :type, '1' %>libvips(DHash)
                        </label>
                        <label class="btn btn-default">
                            <%= f.radio_button :type, '2' %>ImageMagick
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <%= f.label :select_2_images %><br />
                <div class="col-md-12">
                    <div class="form-group dropzone"></div>
                </div>
            </div>
        </div>        
        <%= f.hidden_field :image_id %>
            <%= f.submit(class: 'btn btn-lg btn-block btn-primary', value: 'check', data: { disable_with: "checking..." }) %>
    <% end %>
</div>

app/views/check/result.html.erb
<div class="container-fluid result-container">
    <div class='result text-center <%= @bg_color%>'>
        <p><b><%= @result_message %></b></p>
        Hamming distance : <span><%= @hamming_distance %></span> by <b><%= @type %></b>
    </div>
    <div class="row">
        <% @image_h.each_value { |image| %>
        <div class="col-md-6">
            <div class='text-center'>
                <%= image_tag(image['image'].file.url(:thumb), class: 'preview') if image['image'].file.url.present? %>
            </div>
            <div class="text-center file-name">
                <span><%= image['file_name'] %></span>
            </div>
        </div>
        <% } %>
    </div>
    <div class="back_btn">
        <%= link_to 'back', check_index_path, class: 'btn btn-lg btn-block btn-primary', data: {"turbolinks" => false} %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <head>
    <title>Check the similarity of the images</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <meta name="viewport" content="width=450">
  </head>

  <body>
    <%= yield %>
  </body>
</html>